export const skills = [
    "React",
    "JavaScript",
    "HTML5",
    "CSS3",
    "TypeScript",
    "NextJS",
    "NodeJS",
    "C#",
    ".NET",
    "SQL",
    "noSQL",
    "Git",
    "Bootstrap",
    "Tailwind CSS",
    "Material UI",
    "GraphQL"
];

export const works = [
    {
        title: "Google Photo Clone",
        subtitle: "NodeJS",
        description: "Google Photos clone created with NodeJS and TS, to upload photos, view and create albums.",
        image: "./GooglePhotosClone.png",
        link: "https://github.com/ManuelDiLena/GooglePhotoClone",
    },
    {
        title: "Player Ratings",
        subtitle: "React & NodeJS",
        description: "Complete website with a list of the ratings of the best futbol players.",
        image: "./PlayersRating.png",
        link: "https://github.com/ManuelDiLena/PlayersRatings-front",
    },
    {
        title: "eCommerceNextJS",
        subtitle: "NextJS",
        description: "Complete eCommerce, created with NextJS, React and Styled-components.",
        image: "./SecEcommerce.png",
        link: "https://github.com/ManuelDiLena/eCommerceSec",
    },
    {
        title: "eCommerce",
        subtitle: "React",
        description: "Complete eCommerce, with cart functionality with summary and checkout, created with React.",
        image: "./FirstEcommerce.png",
        link: "https://github.com/ManuelDiLena/eCommerce",
    },
    {
        title: "Hotel Reservation",
        subtitle: "React",
        description: "Hotel reservation website with search filters by date and price, created with React and Redux.",
        image: "./HotelReservation.png",
        link: "https://github.com/ManuelDiLena/HotelReservation",
    },
    {
        title: "Netflix Clone",
        subtitle: "React",
        description: "Netflix web clone, built with React and Redux, using a movie API and Firebase.",
        image: "./NetflixClone.png",
        link: "https://github.com/ManuelDiLena/NetflixClone",
    },
    {
        title: "Spotify Clone",
        subtitle: "React",
        description: "Spotify web clone, built with React and Redux, using a official Spotify API.",
        image: "./SpotifyClone.png",
        link: "https://github.com/ManuelDiLena/SpotifyClone",
    },
    {
        title: "Memo Pad",
        subtitle: "React",
        description: "MemoPad app, where you can create, edit, save and also view them in markdown format.",
        image: "./MemoPad.png",
        link: "https://github.com/ManuelDiLena/MemoPad",
    },
    {
        title: "Wordle Game",
        subtitle: "React",
        description: "Famous game to guess 5 letter words, with 6 chances, created with React and TypeScript.",
        image: "./WordleGame.png",
        link: "https://github.com/ManuelDiLena/WordleGame",
    },
    {
        title: "World Pizza",
        subtitle: "Javascript",
        description: "Pizzeria website built with HTML5, CSS3 and Javascript.",
        image: "./WorldPizza.png",
        link: "https://github.com/ManuelDiLena/WorldPizza",
    },
    {
        title: "Expense App",
        subtitle: "TypeScript",
        description: "App to control expenses and be able to compare between different currencies.",
        image: "./ExpenseApp.png",
        link: "https://github.com/ManuelDiLena/ExpenseApp",
    },
    {
        title: "Tasks App",
        subtitle: "React",
        description: "Task application built with React, in which you can create, finish and delete tasks.",
        image: "./TasksApp.png",
        link: "https://github.com/ManuelDiLena/TasksApp",
    }, 
];