export const skills = [
    "React",
    "JavaScript",
    "HTML5",
    "CSS3",
    "TypeScript",
    "NodeJS",
    "C#",
    ".NET",
    "SQL Server",
    "Firebase",
    "Git",
    "Bootstrap",
    "Tailwind CSS",
    "Material UI"
];

export const works = [
    {
        title: "eCommerce",
        subtitle: "React",
        description: "Complete eCommerce, with cart functionality with summary and checkout, created with React.",
        image: "./FirstEcommerce.png",
        link: "https://github.com/ManuelDiLena/eCommerce",
    },
    {
        title: "Hotel Reservation",
        subtitle: "React",
        description: "Hotel reservation website with search filters by date and price, created with React and Redux.",
        image: "./HotelReservation.png",
        link: "https://github.com/ManuelDiLena/HotelReservation",
    },
    {
        title: "Netflix Clone",
        subtitle: "React",
        description: "Netflix web clone, built with React and Redux, using a movie API and Firebase.",
        image: "./NetflixClone.png",
        link: "https://github.com/ManuelDiLena/NetflixClone",
    },
    {
        title: "Spotify Clone",
        subtitle: "React",
        description: "Spotify web clone, built with React and Redux, using a official Spotify API.",
        image: "./SpotifyClone.png",
        link: "https://github.com/ManuelDiLena/SpotifyClone",
    },
    {
        title: "Memo Pad",
        subtitle: "React",
        description: "MemoPad app, where you can create, edit, save and also view them in markdown format.",
        image: "./MemoPad.png",
        link: "https://github.com/ManuelDiLena/MemoPad",
    },
    {
        title: "World Pizza",
        subtitle: "Javascript",
        description: "Pizzeria website built with HTML5, CSS3 and Javascript.",
        image: "./WorldPizza.png",
        link: "https://github.com/ManuelDiLena/WorldPizza",
    },
    {
        title: "Expense App",
        subtitle: "TypeScript",
        description: "App to control expenses and be able to compare between different currencies.",
        image: "./ExpenseApp.png",
        link: "https://github.com/ManuelDiLena/ExpenseApp",
    },
    {
        title: "Tasks App",
        subtitle: "React",
        description: "Task application built with React, in which you can create, finish and delete tasks.",
        image: "./TasksApp.png",
        link: "https://github.com/ManuelDiLena/TasksApp",
    },
    {
        title: "Book Library",
        subtitle: "React",
        description: "Books page created with React in which you can add new books and view them all.",
        image: "./BookLibrary.png",
        link: "https://github.com/ManuelDiLena/BookLibrary",
    },
    {
        title: "Virtual Keyboard",
        subtitle: "Javascript",
        description: "Virtual keyboard created with Javascript with all its features.",
        image: "./VirtualKeyboard.png",
        link: "https://github.com/ManuelDiLena/VirtualKeyboard",
    },
    {
        title: "Events App",
        subtitle: "Javascript",
        description: "Application to create events with remaining days counter, made with Javascript.",
        image: "./EventsApp.png",
        link: "https://github.com/ManuelDiLena/EventsApp",
    }, 
];